spring:
    datasource:
        url: jdbc:mysql://localhost:3306/jnydy?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        database: mysql
        database-platform: mysql
        hibernate:
            ddl-auto: update # 每次加载实体类更新表
        properties:
            hibernate:
                dialect:
                    org.hibernate.dialect.MySQL57Dialect



